import { defineConfig } from "vite-plus";

// Root config: shared lint/format/staged settings for the whole workspace.
// Vite app config (plugins, server, build) lives in each app's own vite.config.ts.
export default defineConfig({
  staged: {
    "*": "vp check --fix",
  },
  fmt: {},
  lint: {
    // Generated by the MF DTS plugin from each remote; not our source.
    ignorePatterns: ["**/@mf-types/**", "**/dist/**"],
    plugins: ["typescript", "oxc"],
    rules: {
      "vite-plus/prefer-vite-plus-imports": "error",
    },
    options: {
      typeAware: true,
      typeCheck: true,
    },
    jsPlugins: [
      {
        name: "vite-plus",
        specifier: "vite-plus/oxlint-plugin",
      },
    ],
    overrides: [
      {
        files: ["apps/react-remote/**"],
        plugins: ["react"],
        rules: {
          "react/rules-of-hooks": "error",
          "react/only-export-components": [
            "warn",
            {
              allowConstantExport: true,
            },
          ],
        },
      },
    ],
  },
});
